dist: trusty
sudo: false
language: node_js
node_js: 8.8.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
before_deploy:
- yarn global add npm-publish-prerelease
- echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
deploy:
  provider: script
  script: npm-publish-prerelease
  on:
    tags: true
env:
  global:
    secure: GNuDbDMlYtAMXX29d2fGB4PbaAc060p9Y00Z6lgzNPxeFZiFPviRso8jw3O7QRRNpjecCW2k9fB6dQgbkdObIUzmVm6zVJN79yDy3EruSK+L2e82Ws9DjNkOKigPVEG4ftiz4d1Ts/6+lPPGUmxEcCNFnqYrWUNjNarhl6a7lSDqHG5c9QtGtrEYSb9X/o/oawGOVeqllEGyzlWBaieOMYEwPnqkrV1w81NypeTz3pHDaJf/B6OKYBBekBiqOtxfzEWiHr1DAppMWlUqrDBAX1VAwCIQFy927/NcNUsjA7SnobPTTmoG6HCz1O+lieUYYQfPGdu8PckFibgs9GV4EfNKLftBUc2TFUZFmphgg1aemu49D7wDWY8ljtcwMuGQN4JKDfDa12/AXn8+MXXu7Y62ANEfOKoFCPyHSAnzX/RCjc1z1rA2IkCLLyRCbEiI4iDwGlw4KoUIaCkA9YHVlBYBUJX+EPQXyOlPQ+h4ICNRu7EgSE3iO1BbotFbfAQGwd71aoOFKLgs54Cy+UtFLpNdXWDo6PWKRl8aAby16w9zYCws+4buPQ1IOF68I9Ja8jw1vSz/AzUQINqocihlyum8oXBEa5x1O93f8fW4uhlDNWNAFf5b8vzKmx2UHvnBltFumX5NBrQNoJZAJBPrM+cKqRbC5mDyoDL/EXoeIsA=
