version: '2'
services:
  fusion-plugin-universal-events:
    build: .
    volumes:
      - '.:/fusion-plugin-universal-events'
      - /fusion-plugin-universal-events/node_modules/
      - /fusion-plugin-universal-events/dist/
      - /fusion-plugin-universal-events/dist-tests/
    environment:
      - CODECOV_TOKEN
      - CI=true
      - BUILDKITE
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_URL
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_COMMIT
  fusion-plugin-universal-events-node-last:
    extends: fusion-plugin-universal-events
    build:
      context: .
      args:
        BASE_IMAGE: 'uber/web-base-image:1.0.9'
