dist: trusty
sudo: false
language: node_js
node_js: 8.8.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
- export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
before_deploy:
- yarn global add npm-publish-prerelease
- echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
deploy:
  provider: script
  script: npm-publish-prerelease
  on:
    tags: true
env:
  global:
    secure: DhsRhhZjLwdyr/luL/dDJW+bG0lG/pZa0hhjiwbl2pIUv3L6oJ9FcMfRPy4AP3Dt2rTS7tvvB/oIwWq8ssXxbtwE2IJA8sxzoYtY0UfZ7N2rQTS/HTsFg5k71lphP9TTC7RYkhwNRnb2kQCi80suCGwK4elhg/SC3LqXPRRvo09vwixSBlhNrQlYBLxEh7ZwDwmXgsa41/ua+ZGoLMfSoJeojPCeLBQHSK4XXYFY7oW4akpOpB8FRL5nm/wUmT8vNi811q9LVmVulPyh9haH0wrc21PdowkPuAVKNqLw/fJP1+J5h7ki8WBNLdDGjPeUvZMPUGCWHOq0njEwbYjYoFUWeRLMCBdbLFDXCrm8mYrxyq2IhS2Sl3AKhC10QDeEvWnuaiiOl15Fv5ygn9VBeMDFEn87goiciEFitgRoU6y0bmuLBP18/qaH0TJMLkP9uuzXKF4RQ9d1vEy7jaJD0/WROCelnjrKyQh0+R2u1j06ayiKaFRgYRzqnYcY7LsL6HLAWqmoBj5jW/Kxw0J8iY0Wz8Dit613aB8ugj3qtJmUCUsJa3cB7u9vpM+A1dgM8pT02W/iGCQSlkZN98p4YocuJPUapW+aYImLDry5URn7VMmdyvxhUs3mhDTr97elgGFR+zuey5w6GjcHsAHCKIZg5PqEAjNkra47uPFQvbQ=
